apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: asia-southeast2-docker.pkg.dev/cloudapps-poc/app-repo/app
        ports:
        - containerPort: 3000